name: Secure Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

jobs:
  # Job 1: Build and Test
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Tests
      run: |
        python -m unittest discover

  # Job 2: Security Checks
  security_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Static Application Security Testing (Bandit)
      run: |
        pip install bandit
        bandit -r .

    - name: Dependency Vulnerability Scan (Safety)
      uses: pyupio/safety-action@v1
      with: 
        api-key: ${{ secrets.SAFETY_API_KEY }}

    - name: Secret Detection
      uses: yandex/qodana-action@v2023.2
      with:
        languages: python
        linter-options: --secrets

